pipeline {
		agent {
		node {
		label ('built-in')
		}
		}

		stages {
			stage ('create-volume') {
			steps {
			sh "yum install docker -y"
			sh "systemctl start docker"
			sh "docker volume create 22Q1"
			}
			}
			
			stage ('copy-22Q1') {
			steps {
			sh "yum install git -y"
			sh "rm -rf /var/lib/docker/volumes/22Q1/_data"
			sh "git clone https://github.com/ronitunale/dockerassi.git -b 22Q1 /var/lib/docker/volumes/22Q1/_data"
			sh "chmod -R 777 /var/lib/docker/volumes/22Q1/_data"
			}
			}
			
			stage ('Deploy-container') {
			steps {
			sh "docker run --name Branch22Q1 -itdp 90:80 -v 22Q1:/usr/local/apache2/htdocs httpd"
			
			}
						
			}

	}

}
